# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Update nylo.dev
        uses: alikamal1/Form_Data_HTTP_POST_Action@v.1.0
        with:
          url: 'https://nylo.dev/process/site-update'
          headers: '{"Authorization": "Bearer ${{ secrets.NYLO_API_PROCESS_SECRET }}"}'
          data: '{"version": "${{  github.ref_name }}"}'