# .github/workflows/publish.yml
name: Update nylo.dev

on:
  push:
    branches:
    - master

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Update nylo.dev
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://nylo.dev/process/site-update'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.NYLO_API_PROCESS_SECRET }}"}'
          data: '{"version": "${{ github.ref_name }}"}'